config:
  send_anonymous_usage_stats: False
  use_colors: True

default:
  target: "{{ env_var('DBT_DEFAULT_TARGET') }}"
  outputs:
    bq_dev:
      type: bigquery
      method: service-account
      project: "pktech-409212"  # Project ID
      keyfile: "/config/bq_service_account.json"  # Path to your service account key file
      threads: 16
      timeout_seconds: 300
      dataset: reporting  # Replace with your default dataset name
      priority: interactive
      retries: 1
      location: US  # Optional: set this to your BigQuery location, if needed
