# Environments using this will need at least the following environment variables...
# - DBT_PROFILES_DIR=config
# - DBT_DEFAULT_TARGET=/* whatever is appropriate to the target /*
#
# ...plus any other environment variables below for targets used by that environment, e.g. if you're developing in postgres
# - PG_USER=/* your username */
# - PG_PASS=/* your password /*
# - PG_DEV_SCHEMA=/* dbt_dev_{your username} */

config:
    send_anonymous_usage_stats: False
    use_colors: True

default:
  target: "{{ env_var('DBT_DEFAULT_TARGET') }}"
  outputs:
    bq_dev:
      type: bigquery
      method: service-account
      keyfile: config/bq_service_account.json
      project: ff-stadiumgoods-refined-dev
      dataset: "{{ env_var('BQ_DEV_DATASET') }}"
      threads: 16
      timeout_seconds: 300
      priority: interactive
      retries: 1
    bq_stg:
      type: bigquery
      method: service-account
      keyfile: config/bq_service_account.json
      project: ff-stadiumgoods-refined-dev
      dataset: stadiumgoods
      threads: 16
      timeout_seconds: 300
      priority: interactive
      retries: 1
    bq_prod:
      type: bigquery
      method: service-account
      keyfile: config/bq_service_account.json
      project: ff-stadiumgoods-refined-live
      dataset: stadiumgoods
      threads: 16
      timeout_seconds: 300
      priority: interactive
      retries: 1

gitlab-snowflake:
  target: prod
  outputs:
    prod:
      type: snowflake
      threads: 16
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_TRANSFORM_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_TRANSFORM_SCHEMA') }}"
      client_session_keep_alive: True
    ci:
      type: snowflake
      threads: 16
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_TRANSFORM_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_TRANSFORM_SCHEMA') }}"
