version: "3"
services:
  dbt:
    environment:
      - DBT_PROFILES_DIR=config
    env_file:
      - ./dbt/data_warehouse/config/dbt.env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
      - "8001:8001"
    volumes:
      - type: bind
        source: ./dbt/data_warehouse
        target: /dbt/data_warehouse
    stdin_open: true
    tty: true
    working_dir: /dbt/data_warehouse

  etl_service:
    # Define the configuration for your etl_service here
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8100:8100"  # Suggested port for etl_service
      - "8200:8200"  # Another option if needed
    volumes:
      - type: bind
        source: ./_etl_scripts
        target: /_etl_scripts
    # Other configurations (environment, env_file, etc.) as needed
    stdin_open: true
    tty: true
    working_dir: /_etl_scripts
