name: data_warehouse
profile: 'default'
version: 0.0

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

config-version: 2

vars:
  apply_dev_limit: False
  invoking_job_id: '{{ run_started_at.strftime("%Y%m%d%H%M%S") }}'
  service_account: "{{ 'pktech@pktech-409212.iam.gserviceaccount.com' }}"
  project_name: "{{ 'pktech' }}"
  build_from_snapshots: True

clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

on-run-start:
  - "{{ log_invocation_start() }}"
  - "{{ create_udfs() }}"

on-run-end:
  - "{{ grant_schema_permissions() }}"
  - "{{ log_invocation_end() }}"

models:
  data_warehouse:
    pre-hook:
      - "{{ log_model_run_event('start') }}"
    post-hook:
      - "{{ grant_model_permissions() }}"
      - "{{ log_model_run_event('end') }}"
    staging:
      +schema: "{{'staging'}}"
      +materialized: "{{'view'}}"
      +unlogged: True
    sources:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'table' }}"
      +unlogged: True
    reporting:
      +schema: "{{'reporting'}}"
      +materialized: "{{ 'view' }}"
      +unlogged: True
    elementary:
      +schema: "{{'elementary'}}"
      +materialized: "{{ 'view' }}"
      +unlogged: True
    snapshots:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'view' }}"
      +unlogged: True
    seeds:
      +schema: "{{'seeds'}}"
      +materialized: "{{ 'table' }}"
      +unlogged: True
seeds:
  data_warehouse:
    +quote_columns: False
    +enabled: True
    +schema: seeds
    dummy_seed_for_types:
      +column_types:
        text_column: &text_type "{{ 'string' }}"
        float_column: &float_type "{{ 'float64'}}"
        int_column: &int_type "{{ 'int64' }}"
        date_column: &date_type date
        boolean_column: &boolean_type boolean
        bigint_column: &bigint_type "{{ 'int64'}}"
        decimal_column: &decimal_type "{{ 'numeric'}}"
        timestamptz_column: &timestamptz_type "{{ 'timestamp'}}"
    lookup_us_states_info:
      +column_types:
        state: *text_type
        acronym: *text_type
        VAT: *float_type
        Latitude: *float_type
        Longitude: *float_type
