name: piklertech
profile: 'default'
version: 0.0

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]

config-version: 2

vars:
  apply_dev_limit: False
  invoking_job_name: "{{ 'BQ test' if target.type == 'bigquery' else 'Ad hoc' }}"
  invoking_job_id: '{{ run_started_at.strftime("%Y%m%d%H%M%S") }}'
  service_account: "{{ 'dbt-ff-sg-data-live@ff-sg-data-live.iam.gserviceaccount.com' }}"
  project_name: "{{ 'ff-sg-data-live' }}"
  build_from_snapshots: True

clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

on-run-start:
  - "{{ log_invocation_start() }}"
  - "{{ create_udfs() }}"

on-run-end:
  - "{{ grant_schema_permissions() }}"
  - "{{ log_invocation_end() }}"

models:
  stadiumgoods_refined:
    pre-hook:
      - "{{ log_model_run_event('start') }}"
    post-hook:
      - "{{ grant_model_permissions() }}"
      - "{{ log_model_run_event('end') }}"
    staging:
      +schema: "{{'staging'}}"
      +materialized: "{{'view'}}"
      +unlogged: True
    sources:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'view' if target.type == 'bigquery' else 'table' }}"
      +unlogged: True
    reporting:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'view' if target.type == 'bigquery' else 'table' }}"
      +unlogged: True
    elementary:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'view' if target.type == 'bigquery' else 'table' }}"
      +unlogged: True
    snapshots:
      +schema: "{{'sources'}}"
      +materialized: "{{ 'view' if target.type == 'bigquery' else 'table' }}"
      +unlogged: True

seeds:
  stadiumgoods_refined:
    +quote_columns: False
    +enabled: True
    +schema: seeds
    dummy_seed_for_types:
      +column_types:
        text_column: &text_type "{{ 'string' }}"
        float_column: &float_type "{{ 'float64'}}"
        int_column: &int_type "{{ 'int64' }}"
        date_column: &date_type date
        boolean_column: &boolean_type boolean
        bigint_column: &bigint_type "{{ 'int64'}}"
        decimal_column: &decimal_type "{{ 'numeric'}}"
        timestamptz_column: &timestamptz_type "{{ 'timestamp'}}"
#    calendars_dtc_promos:
#      +column_types:
#        promo_date: *date_type
#        promo_type: *text_type
#        discount_amount: *float_type
#        discount_calculation: *text_type
#        promo_note: *text_type
