version: 2

    models:
      - name: product_details
        columns:
          - name: id
            description: 'Primary-key for the products table. Aliased as product_id'
            alias: product_id
          - name: sku
            description: 'Stock keeping unit for the product. Defined as an unique model regardless of size'
          - name: product_size
            description: 'Model size. Alongside sku, assembles an unique unit. American standard of sizes'
          - name: product_name
            description: 'Model name as it is from the StockX website.'
          - name: avg_price
            description: 'Average price which the sku+size was sold on 2023 scraped from StockX'
